server:
  port: 8080
  error:
    whitelabel:
      enabled: true
  # 发现出现中文乱码，则配置下面servlet.encoding.force: true
  servlet:
    encoding:
      force: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
    com:
      spring:
        security:
          learn: DEBUG

spring:
  profiles:
    active: "dev"

# 业务变量
learn:
  jwt:
    access-token-expire-time: 300000
    refresh-token-expire-time: 2592000000
